from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QFileDialog, QPushButton
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(826, 438)
        font = QtGui.QFont()
        font.setPointSize(20)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(60, 90, 421, 151))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 20, 821, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 60, 821, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.help = QtWidgets.QPushButton(self.centralwidget)
        self.help.setGeometry(QtCore.QRect(60, 360, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.help.setFont(font)
        self.help.setObjectName("help")
        self.More = QtWidgets.QPushButton(self.centralwidget)
        self.More.setGeometry(QtCore.QRect(160, 360, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.More.setFont(font)
        self.More.setObjectName("more")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 100, 211, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 160, 221, 16))
        self.label_4.setObjectName("label_4")
        self.chontep_kh = QtWidgets.QPushButton(self.centralwidget)
        self.chontep_kh.setGeometry(QtCore.QRect(370, 130, 75, 23))
        self.chontep_kh.setObjectName("chontep_kh")
        self.path_khachhang = QtWidgets.QLineEdit(self.centralwidget)
        self.path_khachhang.setGeometry(QtCore.QRect(70, 130, 291, 21))
        self.path_khachhang.setObjectName("path_khachhang")
        self.path_cuocgoi = QtWidgets.QLineEdit(self.centralwidget)
        self.path_cuocgoi.setGeometry(QtCore.QRect(70, 190, 291, 21))
        self.path_cuocgoi.setObjectName("path_cuocgoi")
        self.chontep_cg = QtWidgets.QPushButton(self.centralwidget)
        self.chontep_cg.setGeometry(QtCore.QRect(370, 190, 75, 23))
        self.chontep_cg.setObjectName("chontep_cg")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(60, 260, 421, 81))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 270, 121, 16))
        self.label_5.setObjectName("label_5")
        self.path_ketqua = QtWidgets.QLineEdit(self.centralwidget)
        self.path_ketqua.setGeometry(QtCore.QRect(70, 290, 291, 21))
        self.path_ketqua.setObjectName("path_ketqua")
        self.chontep_kq = QtWidgets.QPushButton(self.centralwidget)
        self.chontep_kq.setGeometry(QtCore.QRect(370, 290, 75, 23))
        self.chontep_kq.setObjectName("chontep_kq")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(510, 90, 281, 251))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(530, 130, 121, 16))
        self.label_7.setObjectName("label_7")
        self.ktratiencuoc = QtWidgets.QPushButton(self.centralwidget)
        self.ktratiencuoc.setGeometry(QtCore.QRect(670, 160, 111, 23))
        self.ktratiencuoc.setObjectName("ktratiencuoc")
        self.tongphutgoi = QtWidgets.QPushButton(self.centralwidget)
        self.tongphutgoi.setGeometry(QtCore.QRect(670, 190, 111, 23))
        self.tongphutgoi.setObjectName("tongphutgoi")
        self.hovaten = QtWidgets.QLineEdit(self.centralwidget)
        self.hovaten.setGeometry(QtCore.QRect(530, 160, 113, 20))
        self.hovaten.setObjectName("hovaten")
        self.hovaten_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.hovaten_2.setGeometry(QtCore.QRect(530, 190, 113, 20))
        self.hovaten_2.setObjectName("hovaten_2")
        self.tkadt = QtWidgets.QPushButton(self.centralwidget)
        self.tkadt.setGeometry(QtCore.QRect(580, 242, 161, 61))
        self.tkadt.setObjectName("tkadt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "KhiemVipPro"))
        self.label.setText(_translate("MainWindow", "PHẦN MỀM TÍNH TIỀN ĐIỆN THOẠI"))
        self.label_2.setText(_translate("MainWindow", "Copyright @skromnyy"))
        self.help.setText(_translate("MainWindow", "Help"))
        self.More.setText(_translate("MainWindow", "More"))
        self.label_3.setText(_translate("MainWindow", "Đường dẫn tệp khách hàng sử dụng"))
        self.label_4.setText(_translate("MainWindow", "Đường dẫn tệp cuộc gọi đã được thực hiện"))
        self.chontep_kh.setText(_translate("MainWindow", "Chọn tệp"))
        self.chontep_cg.setText(_translate("MainWindow", "Chọn tệp"))
        self.label_5.setText(_translate("MainWindow", "Đường dẫn tệp thống kê"))
        self.chontep_kq.setText(_translate("MainWindow", "Chọn tệp"))
        self.label_7.setText(_translate("MainWindow", "Lựa chọn"))
        self.ktratiencuoc.setText(_translate("MainWindow", "Kiểm tra số tiền cước"))
        self.tongphutgoi.setText(_translate("MainWindow", "Tổng số phút gọi"))
        self.hovaten.setText(_translate("MainWindow", "0123456789"))
        self.hovaten_2.setText(_translate("MainWindow", "0123456789"))
        self.tkadt.setText(_translate("MainWindow", "Thống kê tổng hợp thông tin"))

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
