# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'decode.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("HUFFMAN CODE")
        MainWindow.resize(767, 415)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 761, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 40, 771, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(60, 70, 681, 271))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 190, 111, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(300, 190, 111, 31))
        self.pushButton1.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 80, 211, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 230, 211, 16))
        self.label_4.setObjectName("label_4")
        self.code = QtWidgets.QLineEdit(self.centralwidget)
        self.code.setGeometry(QtCore.QRect(500, 110, 221, 61))
        self.code.setObjectName("code")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(500, 80, 221, 20))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(500, 190, 221, 20))
        self.label_7.setObjectName("label_7")
        self.freq = QtWidgets.QLineEdit(self.centralwidget)
        self.freq.setGeometry(QtCore.QRect(500, 220, 221, 61))
        self.freq.setText("")
        self.freq.setObjectName("freq")
        self.input = QtWidgets.QTextEdit(self.centralwidget)
        self.input.setGeometry(QtCore.QRect(90, 110, 361, 71))
        self.input.setObjectName("in")
        self.out = QtWidgets.QTextEdit(self.centralwidget)
        self.out.setGeometry(QtCore.QRect(90, 250, 361, 71))
        self.out.setObjectName("out")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 767, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HUFFMAN CODE"))
        self.label_6.setText(_translate("MainWindow", "HUFFMAN CODE"))
        self.label_2.setText(_translate("MainWindow", "Copyright @skromnyy"))
        self.pushButton.setText(_translate("MainWindow", "DECODE"))
        self.pushButton1.setText(_translate("MainWindow", "BACK"))
        self.label_3.setText(_translate("MainWindow", "Đầu vào của chuỗi kí tự cần giải mã"))
        self.label_4.setText(_translate("MainWindow", "Đầu ra của chuỗi đã mã hóa"))
        self.label_5.setText(_translate("MainWindow", "Kí tự có trong đoạn cần giải mã"))
        self.label_7.setText(_translate("MainWindow", "Tần suất lần lượt cách nhau bởi dấu ~"))
